version: "3.8"

services:
  # Exemplos de serviços de API
  testapi:
    image: testapi:1.0
    ports:
      - "5070:5070"


  # Serviço Beyla para `testapi`
  autoinstrumenter_testapi:
    image: grafana/beyla:latest
    pid: "service:testapi"
    privileged: true
    environment:
      BEYLA_OPEN_PORT: 5070
      BEYLA_PROMETHEUS_PORT: 9091 # Porta para expor métricas



  # Serviço Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml